vich_uploader:
    db_driver: orm

    mappings:
        sliderImage:
            uri_prefix: /images/slider_image
            upload_destination: '%kernel.project_dir%/public/images/slider_image'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        menuImage:
            uri_prefix: /images/menu
            upload_destination: '%kernel.project_dir%/public/images/menu'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        pizzas_images:
            uri_prefix: /images/pizzas
            upload_destination: '%kernel.project_dir%/public/images/pizzas'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true
